name: Deploy Trojan Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Trojan Docker image and run
        run: |
          docker pull p4gefau1t/trojan
          docker stop trojan || true
          docker rm trojan || true
          docker run -d --name trojan \
            -p 443:443 \
            -v ${{ github.workspace }}/config.json:/etc/trojan/config.json \
            p4gefau1t/trojan
